spring.application.name=water-demand
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/water_demand_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:water_app}
spring.datasource.password=${DB_PASSWORD:}
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
